-- Setup infrastructure: Warehouse, Database, and Schemas
CREATE WAREHOUSE IF NOT EXISTS AIRLINE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE AIRLINE_WH;
CREATE DATABASE IF NOT EXISTS AIRLINE_DWH;
CREATE SCHEMA IF NOT EXISTS AIRLINE_DWH.RAW;
CREATE SCHEMA IF NOT EXISTS AIRLINE_DWH.STAGE;
CREATE SCHEMA IF NOT EXISTS AIRLINE_DWH.CORE;