-- MANUAL TESTING SCRIPTS (DO NOT AUTOMATE)

-- 1. Initial Data Load (RAW Layer)
-- Load data from internal stage into RAW table
COPY INTO AIRLINE_DWH.RAW.RAW_AIRLINE_DATA 
FROM @AIRLINE_DWH.RAW.MY_INTERNAL_STAGE 
FILE_FORMAT = (FORMAT_NAME = 'AIRLINE_DWH.RAW.CSV_FORMAT') 
ON_ERROR = 'CONTINUE' 
FORCE = TRUE;

-- Check stream to ensure CDC captured the new rows
SELECT COUNT(*) AS RAW_STREAM_COUNT FROM AIRLINE_DWH.RAW.RAW_AIRLINE_STREAM;

-- 2. Execute ETL Procedures
-- Move data RAW -> STAGE
CALL AIRLINE_DWH.STAGE.LOAD_STAGE_AIRLINE_DATA();

-- Check stage stream
SELECT COUNT(*) AS STAGE_STREAM_COUNT FROM AIRLINE_DWH.STAGE.STAGE_AIRLINE_STREAM;

-- Move data STAGE -> CORE
CALL AIRLINE_DWH.CORE.LOAD_CORE_DATA();

-- 3. Verify Audit Logs
-- Check if procedures successfully logged their execution
SELECT * FROM AIRLINE_DWH.CORE.AUDIT_LOG ORDER BY EXECUTION_TIME DESC LIMIT 10;

-- 4. Testing Snowflake Time Travel (DDL Clone)
CREATE OR REPLACE TABLE AIRLINE_DWH.CORE.DIM_PASSENGERS_CLONE 
CLONE AIRLINE_DWH.CORE.DIM_PASSENGERS;

DROP TABLE AIRLINE_DWH.CORE.DIM_PASSENGERS_CLONE;
UNDROP TABLE AIRLINE_DWH.CORE.DIM_PASSENGERS_CLONE;

-- 5. Testing Snowflake Time Travel (DML Recovery)
-- Randomly delete 10 rows
DELETE FROM AIRLINE_DWH.CORE.DIM_PASSENGERS 
WHERE PASSENGER_SK IN (
    SELECT PASSENGER_SK FROM AIRLINE_DWH.CORE.DIM_PASSENGERS LIMIT 10
);

-- Restore the deleted rows using Time Travel (Going back 60 minutes)
INSERT INTO AIRLINE_DWH.CORE.DIM_PASSENGERS
SELECT * FROM AIRLINE_DWH.CORE.DIM_PASSENGERS AT (OFFSET => -60*10)
EXCEPT 
SELECT * FROM AIRLINE_DWH.CORE.DIM_PASSENGERS;

-- 6. Testing Row-Level Security (RLS)
-- Switch to EU_ANALYST role and verify data access (Should only see EU airports)
USE ROLE EU_ANALYST;
USE WAREHOUSE AIRLINE_WH;
USE DATABASE AIRLINE_DWH;
USE SCHEMA CORE;
SELECT * FROM AIRLINE_DWH.CORE.SECURE_VW_FACT_FLIGHTS LIMIT 50;

-- Switch back to ACCOUNTADMIN and verify full data access
USE ROLE ACCOUNTADMIN;
SELECT * FROM AIRLINE_DWH.CORE.SECURE_VW_FACT_FLIGHTS LIMIT 50;