-- Procedure to load data from STAGE to CORE layer (Star Schema)
CREATE OR REPLACE PROCEDURE AIRLINE_DWH.CORE.LOAD_CORE_DATA()
RETURNS STRING LANGUAGE SQL AS
$$
DECLARE
    fact_inserted INT DEFAULT 0;
BEGIN
    BEGIN TRANSACTION; 

    -- Upsert dimensions
    MERGE INTO AIRLINE_DWH.CORE.DIM_PASSENGERS t USING (SELECT DISTINCT PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY FROM AIRLINE_DWH.STAGE.STAGE_AIRLINE_STREAM WHERE METADATA$ACTION = 'INSERT') s
    ON t.PASSENGER_ID = s.PASSENGER_ID WHEN NOT MATCHED THEN INSERT (PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY) VALUES (s.PASSENGER_ID, s.FIRST_NAME, s.LAST_NAME, s.GENDER, s.AGE, s.NATIONALITY);

    MERGE INTO AIRLINE_DWH.CORE.DIM_AIRPORTS t USING (SELECT DISTINCT AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, AIRPORT_CONTINENT, CONTINENTS FROM AIRLINE_DWH.STAGE.STAGE_AIRLINE_STREAM WHERE METADATA$ACTION = 'INSERT') s
    ON t.AIRPORT_NAME = s.AIRPORT_NAME AND t.AIRPORT_COUNTRY_CODE = s.AIRPORT_COUNTRY_CODE WHEN NOT MATCHED THEN INSERT (AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, AIRPORT_CONTINENT, CONTINENTS) VALUES (s.AIRPORT_NAME, s.AIRPORT_COUNTRY_CODE, s.COUNTRY_NAME, s.AIRPORT_CONTINENT, s.CONTINENTS);

    -- Insert facts
    INSERT INTO AIRLINE_DWH.CORE.FACT_FLIGHTS (RECORD_ID, PASSENGER_SK, AIRPORT_SK, DEPARTURE_DATE, ARRIVAL_AIRPORT, PILOT_NAME, FLIGHT_STATUS, TICKET_TYPE, PASSENGER_STATUS)
    SELECT s.RECORD_ID, p.PASSENGER_SK, a.AIRPORT_SK, s.DEPARTURE_DATE, s.ARRIVAL_AIRPORT, s.PILOT_NAME, s.FLIGHT_STATUS, s.TICKET_TYPE, s.PASSENGER_STATUS
    FROM AIRLINE_DWH.STAGE.STAGE_AIRLINE_STREAM s
    LEFT JOIN AIRLINE_DWH.CORE.DIM_PASSENGERS p ON s.PASSENGER_ID = p.PASSENGER_ID
    LEFT JOIN AIRLINE_DWH.CORE.DIM_AIRPORTS a ON s.AIRPORT_NAME = a.AIRPORT_NAME AND s.AIRPORT_COUNTRY_CODE = a.AIRPORT_COUNTRY_CODE
    WHERE s.METADATA$ACTION = 'INSERT';
    
    fact_inserted := SQLROWCOUNT;

    -- Log execution
    INSERT INTO AIRLINE_DWH.CORE.AUDIT_LOG (PROCEDURE_NAME, ROWS_INSERTED, ROWS_UPDATED) VALUES ('LOAD_CORE_DATA', :fact_inserted, 0);

    COMMIT;
    RETURN 'Success: Loaded ' || :fact_inserted || ' facts.';
EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RAISE;
END;
$$;