-- Procedure to clean and cast data from RAW to STAGE
CREATE OR REPLACE PROCEDURE AIRLINE_DWH.STAGE.LOAD_STAGE_AIRLINE_DATA()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    inserted_rows INT DEFAULT 0;
BEGIN
    INSERT INTO AIRLINE_DWH.STAGE.STAGE_AIRLINE_DATA (
        RECORD_ID, PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY, AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME,
        AIRPORT_CONTINENT, CONTINENTS, DEPARTURE_DATE, ARRIVAL_AIRPORT, PILOT_NAME, FLIGHT_STATUS, TICKET_TYPE, PASSENGER_STATUS
    )
    SELECT 
        TRY_CAST(RECORD_ID AS INT), PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, TRY_CAST(AGE AS INT),
        NATIONALITY, AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, AIRPORT_CONTINENT, CONTINENTS, 
        TRY_TO_DATE(DEPARTURE_DATE, 'MM/DD/YYYY'), ARRIVAL_AIRPORT, PILOT_NAME, FLIGHT_STATUS, TICKET_TYPE, PASSENGER_STATUS
    FROM AIRLINE_DWH.RAW.RAW_AIRLINE_STREAM
    WHERE METADATA$ACTION = 'INSERT';
    
    inserted_rows := SQLROWCOUNT;

    INSERT INTO AIRLINE_DWH.CORE.AUDIT_LOG (PROCEDURE_NAME, ROWS_INSERTED, ROWS_UPDATED)
    VALUES ('LOAD_STAGE_AIRLINE_DATA', :inserted_rows, 0);

    RETURN 'Success: Loaded ' || :inserted_rows || ' rows into STAGE.';
END;
$$;