-- Create dimension table for airports
CREATE OR REPLACE TABLE AIRLINE_DWH.CORE.DIM_AIRPORTS (
    AIRPORT_SK INT AUTOINCREMENT PRIMARY KEY, 
    AIRPORT_NAME VARCHAR, 
    AIRPORT_COUNTRY_CODE VARCHAR, 
    COUNTRY_NAME VARCHAR, 
    AIRPORT_CONTINENT VARCHAR, 
    CONTINENTS VARCHAR
);