-- Create dimension table for passengers
CREATE OR REPLACE TABLE AIRLINE_DWH.CORE.DIM_PASSENGERS (
    PASSENGER_SK INT AUTOINCREMENT PRIMARY KEY, 
    PASSENGER_ID VARCHAR, 
    FIRST_NAME VARCHAR, 
    LAST_NAME VARCHAR, 
    GENDER VARCHAR, 
    AGE INT, 
    NATIONALITY VARCHAR
);