-- Create fact table for flights
CREATE OR REPLACE TABLE AIRLINE_DWH.CORE.FACT_FLIGHTS (
    RECORD_ID INT PRIMARY KEY, 
    PASSENGER_SK INT, 
    AIRPORT_SK INT, 
    DEPARTURE_DATE DATE, 
    ARRIVAL_AIRPORT VARCHAR, 
    PILOT_NAME VARCHAR, 
    FLIGHT_STATUS VARCHAR, 
    TICKET_TYPE VARCHAR, 
    PASSENGER_STATUS VARCHAR, 
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);