-- Create file format for CSV parsing
CREATE OR REPLACE FILE FORMAT AIRLINE_DWH.RAW.CSV_FORMAT 
    TYPE = 'CSV' 
    FIELD_DELIMITER = ',' 
    SKIP_HEADER = 1 
    FIELD_OPTIONALLY_ENCLOSED_BY = '"' 
    NULL_IF = ('NULL', 'null', '')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;
-- Create internal stage for file uploads
CREATE OR REPLACE STAGE AIRLINE_DWH.RAW.MY_INTERNAL_STAGE
    FILE_FORMAT = AIRLINE_DWH.RAW.CSV_FORMAT;
-- Create raw table with all columns as VARCHAR to prevent load failures
CREATE OR REPLACE TABLE AIRLINE_DWH.RAW.RAW_AIRLINE_DATA (
    RECORD_ID VARCHAR, PASSENGER_ID VARCHAR, FIRST_NAME VARCHAR, LAST_NAME VARCHAR,
    GENDER VARCHAR, AGE VARCHAR, NATIONALITY VARCHAR, AIRPORT_NAME VARCHAR,
    AIRPORT_COUNTRY_CODE VARCHAR, COUNTRY_NAME VARCHAR, AIRPORT_CONTINENT VARCHAR,
    CONTINENTS VARCHAR, DEPARTURE_DATE VARCHAR, ARRIVAL_AIRPORT VARCHAR,
    PILOT_NAME VARCHAR, FLIGHT_STATUS VARCHAR, TICKET_TYPE VARCHAR,
    PASSENGER_STATUS VARCHAR, LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);