-- Create stage table with proper data types
CREATE OR REPLACE TABLE AIRLINE_DWH.STAGE.STAGE_AIRLINE_DATA (
    RECORD_ID INT, PASSENGER_ID VARCHAR, FIRST_NAME VARCHAR, LAST_NAME VARCHAR,
    GENDER VARCHAR, AGE INT, NATIONALITY VARCHAR, AIRPORT_NAME VARCHAR,
    AIRPORT_COUNTRY_CODE VARCHAR, COUNTRY_NAME VARCHAR, AIRPORT_CONTINENT VARCHAR,
    CONTINENTS VARCHAR, DEPARTURE_DATE DATE, ARRIVAL_AIRPORT VARCHAR,
    PILOT_NAME VARCHAR, FLIGHT_STATUS VARCHAR, TICKET_TYPE VARCHAR,
    PASSENGER_STATUS VARCHAR, LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);