-- Create secure view for fact flights to apply security policies
CREATE OR REPLACE SECURE VIEW AIRLINE_DWH.CORE.SECURE_VW_FACT_FLIGHTS AS
SELECT f.RECORD_ID, f.DEPARTURE_DATE, f.ARRIVAL_AIRPORT, f.FLIGHT_STATUS, a.AIRPORT_CONTINENT 
FROM AIRLINE_DWH.CORE.FACT_FLIGHTS f 
JOIN AIRLINE_DWH.CORE.DIM_AIRPORTS a ON f.AIRPORT_SK = a.AIRPORT_SK;
