-- Create Row Access Policy to restrict data visibility based on roles
CREATE OR REPLACE ROW ACCESS POLICY AIRLINE_DWH.CORE.REGION_POLICY 
AS (airport_continent VARCHAR) RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN') THEN TRUE
        WHEN CURRENT_ROLE() = 'EU_ANALYST' AND airport_continent = 'EU' THEN TRUE
        ELSE FALSE
    END;

-- Apply policy to the secure view
ALTER VIEW AIRLINE_DWH.CORE.SECURE_VW_FACT_FLIGHTS 
ADD ROW ACCESS POLICY AIRLINE_DWH.CORE.REGION_POLICY ON (AIRPORT_CONTINENT);    

-- Set up roles and grant privileges
CREATE ROLE IF NOT EXISTS EU_ANALYST;
GRANT USAGE ON WAREHOUSE AIRLINE_WH TO ROLE EU_ANALYST;
GRANT USAGE ON DATABASE AIRLINE_DWH TO ROLE EU_ANALYST;
GRANT USAGE ON SCHEMA AIRLINE_DWH.CORE TO ROLE EU_ANALYST;
GRANT SELECT ON VIEW AIRLINE_DWH.CORE.SECURE_VW_FACT_FLIGHTS TO ROLE EU_ANALYST;

-- Assign role to specific user
GRANT ROLE EU_ANALYST TO USER ICECREAMMAN87;